services:
  app:
    image: codeberg.org/readeck/readeck:latest
    container_name: readeck
    ports:
      - 8030:8000
    environment:
      - READECK_SERVER_PORT=${READECK_SERVER_PORT}
      - READECK_SERVER_PREFIX=${READECK_SERVER_PREFIX}
      - READECK_ALLOWED_HOSTS=${READECK_ALLOWED_HOSTS}
      - READECK_USE_X_FORWARDED=${READECK_USE_X_FORWARDED}      
    volumes:
      - /mnt/cephfs/stacks/readeck/data:/readeck
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/readeck", "healthcheck", "-config", "config.toml"]
      interval: 30s
      timeout: 2s
      retries: 3