services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-mate
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - TITLE=Webtop1 #optional
    volumes:
      - ~/apps/webtop/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri/renderD128:/dev/dri
    shm_size: "1gb" #optional
    restart: unless-stopped