services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    restart: always
    ports:
      - '8011:8080'
    volumes:
      - /mnt/cephfs/stacks/pdf/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - /mnt/cephfs/stacks/pdf/extraConfigs:/configs
      - /mnt/cephfs/stacks/pdf/customFiles:/customFiles/
      - /mnt/cephfs/stacks/pdf/logs:/logs/