services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    volumes:
      - /mnt/cephfs/stacks/code-server/config:/config
    environment:
      - PUID=0
      - PGID=0    
      - HASHED_PASSWORD=${HASHED_PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - DEFAULT_WORKSPACE=/config/workspace
      - PROXY_DOMAIN=code.compucade.us
    ports:
      - 8043:8443
    restart: unless-stopped