---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    volumes:
      - /home/compukid/apps/code-server/config:/config
    env_file:
      - /home/compukid/apps/.secrets/code.env
      - /home/compukid/apps/.secrets/default.env
    ports:
      - 8043:8443
    restart: unless-stopped
