services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "8014:80/tcp"
    # Volumes store your data between container upgrades
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
    env_file:
      - /home/compukid/apps/.secrets/default.env
    restart: unless-stopped
