#version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - /mnt/cephfs/stacks/kuma/data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped