# Running `docker-compose up` will create/use the "trilium-data" directory in the user home
# Run `TRILIUM_DATA_DIR=/path/of/your/choice docker-compose up` to set a different directory
services:
  trilium:
    image: zadam/trilium
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    ports:
      - "8012:8080"
    volumes:
      - /home/compukid/apps/trilium/data:/home/node/trilium-data
    env_file:
      - path: ~/apps/.secrets/default.env

volumes:
  trilium:
