services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS= #optional
      - SETTINGS_ENCRYPTION_KEY=${ENCRYPTION_KEY}      
    volumes:
      - /mnt/cephfs/stacks/duplicati/config:/config
      - /mnt/cephfs/stacks/duplicati/backups:/backups
      - /:/source
    ports:
      - 8201:8200
    restart: unless-stopped